from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import os
import tempfile
import yt_dlp
import atexit

app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})

def get_format_string(quality: str):
    """Return yt-dlp format string based on requested quality"""
    quality = quality.lower()
    if quality == '1080p':
        return 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best[height<=1080][ext=mp4]'
    elif quality == '720p':
        return 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best[height<=720][ext=mp4]'
    elif quality == '360p':
        return 'best[height<=360][ext=mp4]'
    return 'best[ext=mp4]'

@app.route("/", methods=["GET"])
def home():
    return "YouTube Downloader Backend Running!"

# Folder to save downloaded videos temporarily
DOWNLOADS_DIR = os.path.join(os.getcwd(), "downloads")
os.makedirs(DOWNLOADS_DIR, exist_ok=True)

@app.route("/download", methods=["POST"])
def download_video():
    try:
        data = request.json
        if not data or "url" not in data:
            return jsonify({"error": "URL is required"}), 400

        url = data["url"].strip()
        quality = data.get("quality", "360p").lower()
        format_code = get_format_string(quality)

        # Extract video info for a safe filename
        ydl_opts_meta = {'quiet': True, 'skip_download': True}
        with yt_dlp.YoutubeDL(ydl_opts_meta) as ydl:
            info_dict = ydl.extract_info(url, download=False)
            from yt_dlp.utils import sanitize_filename
            filename = sanitize_filename(info_dict.get('title', 'video')) + f'-{quality}.mp4'

        file_path = os.path.join(DOWNLOADS_DIR, filename)

        # --- Handle cookies ---
        # Option 1: Inline cookies (replace <YOUR_COOKIES_HERE> with actual browser-exported cookies)
        INLINE_COOKIES = """
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	TRUE	1759007428	GPS	1
.youtube.com	TRUE	/	TRUE	1790541630	__Secure-1PSIDTS	sidts-CjQBmkD5S-uRHM406W_F4J7aCfkq-tv96uYSnw-WO_vmNNMSSAXUanXdnGPBsNUZX33O7W_CEAA
.youtube.com	TRUE	/	TRUE	1790541630	__Secure-3PSIDTS	sidts-CjQBmkD5S-uRHM406W_F4J7aCfkq-tv96uYSnw-WO_vmNNMSSAXUanXdnGPBsNUZX33O7W_CEAA
.youtube.com	TRUE	/	TRUE	1793565630	__Secure-3PAPISID	qN8ejfWiWsJLdCx8/AldKrcogl6lxZPNWo
.youtube.com	TRUE	/	TRUE	1793565630	__Secure-3PSID	g.a0001Qh4CZLLRR2GyDazt7oefv8J7tfTkhFTruInjpFYjNme3IE3aF1Voqm5MhwBozth1OxS4QACgYKATwSARASFQHGX2MisHHxJEU6hV4nmLLGlrFN0RoVAUF8yKquLRZkDIkco3OMsUYZBdMG0076
.youtube.com	TRUE	/	FALSE	0	PREF	f6=40000000&tz=UTC&hl=en
.youtube.com	TRUE	/	TRUE	1793565631	LOGIN_INFO	AFmmF2swRQIgJLrIeyRRUwJZ_Ly1aKhs_4HsVWh4T7H4S5cVtFLwoyACIQDD-f1eoii1s7w8mSAO01wLV1maiJ5GaGQn5jKEzER5jg:QUQ3MjNmeUxydThGajFuNXZpZ0U5Z3dfSmVSYTR0aDE2YXg0bnh4RFZ2NkhlWk1FLWxnSXdVVVdiUXNEdTJQSVR6ZXZ0QVJoZEtUVTI4eFFFU3hRaGJrTjZqTVpRMVJqZDFuNjhKSXotaXRTakREUW9iR0VUOF9LYUREWUZDWXZxZHYzQ2pJVHZqenVyUXZjQnFERlhjdUJ0dmQ0c0Fwd0VB
.youtube.com	TRUE	/	TRUE	1790541717	__Secure-3PSIDCC	AKEyXzXQ4zrrFN6-QiKuJEiI_r4ic2hmWuK34cQSlKeSsJZX1Ase1MJQwgSyYJTkochoHl1D
.youtube.com	TRUE	/	TRUE	0	YSC	fl_PFPSnv38
.youtube.com	TRUE	/	TRUE	1774557717	VISITOR_INFO1_LIVE	3IByPNfa0qA
.youtube.com	TRUE	/	TRUE	1774557717	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgEg%3D%3D
.youtube.com	TRUE	/	TRUE	1774557630	__Secure-ROLLOUT_TOKEN	CIzkw6Pkxqy0PhDi5P_M5vmPAxjYmovO5vmPAw%3D%3D
.youtube.com	TRUE	/	TRUE	1822077717	__Secure-YT_TVFAS	t=488612&s=2
.youtube.com	TRUE	/	TRUE	1774557717	DEVICE_INFO	ChxOelUxTkRnM01qQXlPVFE1TlRVek16YzJOZz09EJWY4cYGGJWY4cYG
.youtube.com	TRUE	/tv	TRUE	1791837717	__Secure-YT_DERP	CITsn6Z7
"""

        cookies_content = os.environ.get("YOUTUBE_COOKIES", INLINE_COOKIES.strip())
        cookie_file_path = None

        if cookies_content:
            # Write cookies to temporary file
            tmp = tempfile.NamedTemporaryFile(delete=False, mode='w', encoding='utf-8')
            tmp.write(cookies_content)
            tmp.close()
            cookie_file_path = tmp.name

            # Auto-remove temp cookie file on exit
            atexit.register(lambda: os.remove(cookie_file_path) if os.path.exists(cookie_file_path) else None)

        # yt-dlp options
        ydl_opts_final = {
            'quiet': True,
            'no_warnings': True,
            'outtmpl': file_path,
            'format': format_code,
            'merge_output_format': 'mp4',
            'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                          '(KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
            'geo_bypass': True,
        }

        if cookie_file_path:
            ydl_opts_final['cookiefile'] = cookie_file_path

        # Download video
        with yt_dlp.YoutubeDL(ydl_opts_final) as ydl:
            ydl.download([url])

        # Send video to frontend
        return send_file(
            file_path,
            as_attachment=True,
            download_name=filename,
            mimetype="video/mp4"
        )

    except yt_dlp.utils.DownloadError as e:
        print("DownloadError:", e)
        error_msg = f"Download failed: {str(e).split(': ')[-1].split(';')[0].strip()}"
        if "HTTP Error 403" in str(e):
            error_msg += ". Video may be restricted/geo-blocked. Check cookies."
        return jsonify({"error": error_msg}), 500

    except Exception as e:
        print("Exception:", e)
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
